name: EssentialsPlugin
version: 1.0.0
main: org.gabooj.EssentialsPlugin
description: Gabe's essentials plugin
author: PaperMC
api-version: '1.21.3'
commands:
  chat:
      description: A command to change how your chat is displayed. Use /chat for more information!
      usage: /chat
  claim:
    description: A command to claim the chunk you are in, in the overworld. Use /claim to claim your chunk!
    usage: /claim
  unclaim:
    description: A command to unclaim land in the overworld. Use /unclaim to unclaim your chunks.
    usage: /unclaim
  setclaim:
    description: An OP command to set the claim of the chunk you are in. Use /setclaim <name> to set the claim of a given chunk!
    usage: /setclaim
  map:
    description: A command to show a map of claimed chunks around you. Use /map or /map <radius> to display a map of claims.
    usage: /map
  friend:
    description: A command to add/remove friends that will have full access to your claimed land.
    usage: /friend
  info:
    description: A command to list server information.
    usage: /info
  commands:
    description: A command to list custom server commands.
    usage: /commands
  rules:
    description: A command to list server rules.
    usage: /rules
  mail:
    description: A command to send and receive mail, even when players are online.
    usage: /mail
  warp:
    description: A command to teleport you to a warp location.
    usage: /warp
  tpa:
    description: A command to request to teleport to other players.
    usage: /tpa
  home:
    description: A command to teleport you to your bed.
    usage: /home
  showhand:
    description: A command to show the item held in your hand to the server.
    usage: /showhand